version: "3.9"

services:
  server:
    image: jaykay24/issue-tracker-server:1.0.0
    ports:
      - "3000:3000"
    restart: always
  client:
    depends_on:
      - server
    image: jaykay24/issue-tracker-client:1.0.0
    ports:
      - "3001:3001"
    restart: always